CREATE DATABASE lunch_go_where;

GRANT ALL PRIVILEGES ON DATABASE lunch_go_where TO sohsinghian;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public to sohsinghian;

BEGIN;

CREATE TABLE restaurants (
    id SERIAL NOT NULL PRIMARY KEY UNIQUE,
    name VARCHAR(60) NOT NULL
);

COMMIT;

ANALYZE restaurants;